upstream praxisflow_frontend {
  server frontend:3000;
}

upstream praxisflow_backend {
  server backend:8000;
}

server {
  listen 80;
  location /api/ {
    proxy_pass http://praxisflow_backend;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
  location / {
    proxy_pass http://praxisflow_frontend;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
