"""
Security Module for PraxisFlow
RBAC/ABAC authorization, encryption, tenant isolation middleware.
"""

from app.security.base import (
    Role,
    Permission,
    AttributeKey,
    Subject,
    Resource,
    Action,
    AuthorizationDecision,
    PolicyEngine,
    OPAPolicyEngine,
    RBACManager,
    ABACManager,
    AuthorizationService,
    get_current_subject,
    require_permission,
    meeting_resource,
    task_resource,
    integration_resource,
)
from app.security.secrets import (
    VaultConfig,
    AWSSecretsConfig,
    SecretsBackend,
    VaultBackend,
    AWSSecretsBackend,
    EnvBackend,
    SecretsManager,
    SecretNotFoundError,
    SecretsBackendError,
    get_secrets_manager,
    get_secret,
    set_secret,
    delete_secret,
    get_database_url,
    get_groq_api_key,
    get_openai_api_key,
    get_anthropic_api_key,
    get_deepgram_api_key,
    get_jwt_secret,
    get_redis_url,
    get_kafka_bootstrap_servers,
    get_neo4j_credentials,
    get_qdrant_credentials,
    get_minio_credentials,
    get_langfuse_keys,
    get_clerk_keys,
    get_integration_secrets,
)
from app.security.encryption import (
    EncryptionManager,
    EnvelopeEncryption,
    get_encryption_manager,
    encrypt_field,
    decrypt_field,
    rotate_key,
)
from app.security.middleware import (
    TenantIsolationMiddleware,
    RateLimitMiddleware,
    SecurityHeadersMiddleware,
    RequestValidationMiddleware,
    AuditLoggingMiddleware,
    get_cors_config,
    build_security_middleware_stack,
)

__all__ = [
    # RBAC/ABAC
    "Role",
    "Permission",
    "AttributeKey",
    "Subject",
    "Resource",
    "Action",
    "AuthorizationDecision",
    "PolicyEngine",
    "OPAPolicyEngine",
    "RBACManager",
    "ABACManager",
    "AuthorizationService",
    "get_current_subject",
    "require_permission",
    "meeting_resource",
    "task_resource",
    "integration_resource",
    # Secrets
    "VaultConfig",
    "AWSSecretsConfig",
    "SecretsBackend",
    "VaultBackend",
    "AWSSecretsBackend",
    "EnvBackend",
    "SecretsManager",
    "SecretNotFoundError",
    "SecretsBackendError",
    "get_secrets_manager",
    "get_secret",
    "set_secret",
    "delete_secret",
    "get_database_url",
    "get_groq_api_key",
    "get_openai_api_key",
    "get_anthropic_api_key",
    "get_deepgram_api_key",
    "get_jwt_secret",
    "get_redis_url",
    "get_kafka_bootstrap_servers",
    "get_neo4j_credentials",
    "get_qdrant_credentials",
    "get_minio_credentials",
    "get_langfuse_keys",
    "get_clerk_keys",
    "get_integration_secrets",
    # Encryption
    "EncryptionManager",
    "EnvelopeEncryption",
    "get_encryption_manager",
    "encrypt_field",
    "decrypt_field",
    "rotate_key",
    # Middleware
    "TenantIsolationMiddleware",
    "RateLimitMiddleware",
    "SecurityHeadersMiddleware",
    "RequestValidationMiddleware",
    "AuditLoggingMiddleware",
    "get_cors_config",
    "build_security_middleware_stack",
]