-- ============================================================================
-- PraxisFlow — Row-Level Security setup
-- ============================================================================
-- Apply AFTER `prisma db push`:
--
--   psql "$DATABASE_URL" -f infrastructure/docker/rls-setup.sql
--
-- What this does:
--   1. Creates a dedicated application role `praxisflow_app` that does NOT
--      own tables and does NOT have BYPASSRLS.
--   2. Enables RLS on every tenant-bearing table (PascalCase names
--      as generated by Prisma).
--   3. Creates per-table policies keyed on current_setting('app.current_tenant').
--
-- How the app satisfies policies:
--   Every request/transaction must set app.current_tenant on ITS OWN
--   connection. The Prisma runtime proxy does this inside each transaction;
--   explicit multi-operation transactions use app.db.prisma.tenant_tx():
--
--       async with tenant_tx(db) as tx:
--           meetings = await tx.meeting.find_many(...)
--
-- Tables WITHOUT a tenantId column (Transcript, Utterance, Attendee,
-- MeetingFlag, TaskAuditLog) are scoped through their parent relation using
-- EXISTS subqueries in the policies below. AiAuditLog carries tenantId and
-- is covered directly.
--
-- NOTE: The connection user in DATABASE_URL must be `praxisflow_app` for RLS
-- to bind. Table owners and superusers bypass RLS entirely.
-- ============================================================================

BEGIN;

-- ─── 1. Application role ────────────────────────────────────────────────────
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'praxisflow_app') THEN
        CREATE ROLE praxisflow_app LOGIN PASSWORD NULL;  -- password set by operator
    END IF;
END
$$;

ALTER ROLE praxisflow_app NOBYPASSRLS;

-- Webhook receivers carry no tenant JWT. Use a separate read-only role that
-- can inspect only the columns needed to find and verify an integration.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'praxisflow_webhook_lookup') THEN
        CREATE ROLE praxisflow_webhook_lookup LOGIN BYPASSRLS PASSWORD NULL;
    END IF;
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO praxisflow_webhook_lookup', current_database());
END
$$;
GRANT USAGE ON SCHEMA public TO praxisflow_webhook_lookup;
GRANT SELECT ("id", "tenantId", "provider", "status", "webhookSecret")
    ON "Integration" TO praxisflow_webhook_lookup;

-- Schema-wide grants for the app role
GRANT USAGE ON SCHEMA public TO praxisflow_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO praxisflow_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO praxisflow_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO praxisflow_app;

-- Keep LangGraph checkpoints outside the tenant data schema. The application
-- role can create checkpoint tables here without CREATE rights in public.
CREATE SCHEMA IF NOT EXISTS langgraph AUTHORIZATION praxisflow_app;
GRANT USAGE, CREATE ON SCHEMA langgraph TO praxisflow_app;

-- The scheduled backup process needs a complete logical dump, including rows
-- protected by RLS, but must not be able to modify application data.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'praxisflow_backup') THEN
        CREATE ROLE praxisflow_backup LOGIN BYPASSRLS PASSWORD NULL;
    END IF;
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO praxisflow_backup', current_database());
END
$$;
ALTER ROLE praxisflow_backup NOINHERIT;
GRANT USAGE ON SCHEMA public, langgraph TO praxisflow_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA public, langgraph TO praxisflow_backup;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public, langgraph TO praxisflow_backup;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO praxisflow_backup;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON SEQUENCES TO praxisflow_backup;
ALTER DEFAULT PRIVILEGES FOR ROLE praxisflow_app IN SCHEMA langgraph
    GRANT SELECT ON TABLES TO praxisflow_backup;
ALTER DEFAULT PRIVILEGES FOR ROLE praxisflow_app IN SCHEMA langgraph
    GRANT SELECT ON SEQUENCES TO praxisflow_backup;

-- ─── 2. Helper: current tenant from GUC (empty string when unset = deny) ───
CREATE OR REPLACE FUNCTION current_tenant_id() RETURNS text AS $$
    SELECT COALESCE(current_setting('app.current_tenant', true), '');
$$ LANGUAGE sql STABLE;

-- ─── 3. Enable RLS on all tenant-scoped tables ─────────────────────────────
-- ENABLE only (no FORCE): the table OWNER (migration/seed role) keeps
-- bypass so dev flows and `prisma db push` work unchanged. Every NON-owner
-- role — i.e. `praxisflow_app`, the intended runtime identity — is fully
-- constrained by the policies below.
--
-- If you want zero-bypass hardening later, apply FORCE per table knowing
-- that ALL roles then require `SET app.current_tenant` first.
DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'Tenant', 'User', 'Meeting', 'Task', 'Integration', 'AiAuditLog',
        'DataSubjectRequest', 'ComplianceExport', 'HumanReview',
        -- child tables: scoped through parent-relation policies
        'Transcript', 'Utterance', 'Attendee', 'MeetingFlag', 'TaskAuditLog'
    ]
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    END LOOP;
END
$$;

-- ─── 4. Policies: direct tenantId columns ──────────────────────────────────
-- Tenant row itself: readable only when it IS the context tenant
DROP POLICY IF EXISTS tenant_isolation ON "Tenant";
CREATE POLICY tenant_isolation ON "Tenant"
    USING ("id"::text = current_tenant_id());

DROP POLICY IF EXISTS tenant_isolation ON "User";
CREATE POLICY tenant_isolation ON "User"
    USING ("tenantId" = current_tenant_id())
    WITH CHECK ("tenantId" = current_tenant_id());

DROP POLICY IF EXISTS tenant_isolation ON "Meeting";
CREATE POLICY tenant_isolation ON "Meeting"
    USING ("tenantId" = current_tenant_id())
    WITH CHECK ("tenantId" = current_tenant_id());

DROP POLICY IF EXISTS tenant_isolation ON "Task";
CREATE POLICY tenant_isolation ON "Task"
    USING ("tenantId" = current_tenant_id())
    WITH CHECK ("tenantId" = current_tenant_id());

DROP POLICY IF EXISTS tenant_isolation ON "Integration";
CREATE POLICY tenant_isolation ON "Integration"
    USING ("tenantId" = current_tenant_id())
    WITH CHECK ("tenantId" = current_tenant_id());

DROP POLICY IF EXISTS tenant_isolation ON "AiAuditLog";
CREATE POLICY tenant_isolation ON "AiAuditLog"
    USING ("tenantId" = current_tenant_id())
    WITH CHECK ("tenantId" = current_tenant_id());

DROP POLICY IF EXISTS tenant_isolation ON "DataSubjectRequest";
CREATE POLICY tenant_isolation ON "DataSubjectRequest"
    USING ("tenantId" = current_tenant_id())
    WITH CHECK ("tenantId" = current_tenant_id());

DROP POLICY IF EXISTS tenant_isolation ON "ComplianceExport";
CREATE POLICY tenant_isolation ON "ComplianceExport"
    USING ("tenantId" = current_tenant_id())
    WITH CHECK ("tenantId" = current_tenant_id());

DROP POLICY IF EXISTS tenant_isolation ON "HumanReview";
CREATE POLICY tenant_isolation ON "HumanReview"
    USING ("tenantId" = current_tenant_id())
    WITH CHECK ("tenantId" = current_tenant_id());

-- ─── 5. Policies: child tables scoped through parents ──────────────────────
DROP POLICY IF EXISTS tenant_isolation ON "Transcript";
CREATE POLICY tenant_isolation ON "Transcript"
    USING (
        EXISTS (
            SELECT 1 FROM "Meeting" m
            WHERE m."id" = "meetingId" AND m."tenantId" = current_tenant_id()
        )
    );

DROP POLICY IF EXISTS tenant_isolation ON "Utterance";
CREATE POLICY tenant_isolation ON "Utterance"
    USING (
        EXISTS (
            SELECT 1 FROM "Transcript" tr
            JOIN "Meeting" m ON m."id" = tr."meetingId"
            WHERE tr."id" = "transcriptId" AND m."tenantId" = current_tenant_id()
        )
    );

DROP POLICY IF EXISTS tenant_isolation ON "Attendee";
CREATE POLICY tenant_isolation ON "Attendee"
    USING (
        EXISTS (
            SELECT 1 FROM "Meeting" m
            WHERE m."id" = "meetingId" AND m."tenantId" = current_tenant_id()
        )
    );

DROP POLICY IF EXISTS tenant_isolation ON "MeetingFlag";
CREATE POLICY tenant_isolation ON "MeetingFlag"
    USING (
        EXISTS (
            SELECT 1 FROM "Meeting" m
            WHERE m."id" = "meetingId" AND m."tenantId" = current_tenant_id()
        )
    );

DROP POLICY IF EXISTS tenant_isolation ON "TaskAuditLog";
CREATE POLICY tenant_isolation ON "TaskAuditLog"
    USING (
        EXISTS (
            SELECT 1 FROM "Task" tk
            WHERE tk."id" = "taskId" AND tk."tenantId" = current_tenant_id()
        )
    );

COMMIT;

-- ============================================================================
-- Operator checklist:
--   1. psql "$ADMIN_URL" -c "ALTER ROLE praxisflow_app PASSWORD '<secret>';"
--   2. Point DATABASE_URL at role praxisflow_app (NOT postgres/superuser).
--   3. Ensure every request transaction sets app.current_tenant first
--      (app.db.prisma.tenant_tx).
-- ============================================================================
